version: '3.9'

services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:19.0.3
    environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - .\keycloak-config:/config
      - .\keycloak-config\keycloak_config.json:/opt/keycloak/data/import/keycloak_config.json:ro
    ports:
      - "8080:8080"
    entrypoint: '/opt/keycloak/bin/kc.sh start-dev --import-realm'

