version: '3.9'

services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:19.0.3
    environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak-config:/config
      - ./keycloak-config/TCM-realm.json:/opt/keycloak/data/import/TCM-realm.json:ro
      - ./keycloak-config:/tmp/export
    ports:
      - "8080:8080"
    entrypoint: '/opt/keycloak/bin/kc.sh start-dev --import-realm'

